parameters:


services:
  Platformsh\Client\Connection\Connector:
    class: Platformsh\Client\Connection\Connector
    arguments: [~,~]

  Platformsh\Client\PlatformClient:
    class: Platformsh\Client\PlatformClient
    arguments:
      - '@Platformsh\Client\Connection\Connector'
