parameters:


services:
  platform.connection:
    class: Platformsh\Client\Connection\Connector
    arguments: [~,~]

  platform.client:
    class: Platformsh\Client\PlatformClient
    arguments:
      - '@platform.connection'
